"""Add chat session and message tables

Revision ID: 1347f77b4db9
Revises: 20260113_0004
Create Date: 2026-01-20 09:19:51.772823+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1347f77b4db9'
down_revision = '20260113_0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_chat_session_last_activity_at'), 'chat_session', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_chat_session_user_id'), 'chat_session', ['user_id'], unique=False)
    op.create_table('chat_message',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.session_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_chat_message_created_at'), 'chat_message', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_message_session_id'), 'chat_message', ['session_id'], unique=False)
    op.alter_column('todo', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               comment=None,
               existing_comment='Unique todo identifier',
               existing_nullable=False)
    op.alter_column('todo', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Owner of the todo (foreign key to users.id, CASCADE on delete)',
               existing_nullable=False)
    op.alter_column('todo', 'title',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Todo title/summary (1-500 characters)',
               existing_nullable=False)
    op.alter_column('todo', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               comment=None,
               existing_comment='Optional detailed description',
               existing_nullable=True)
    op.alter_column('todo', 'completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment=None,
               existing_comment='Completion status (default: false)',
               existing_nullable=False)
    op.alter_column('todo', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment=None,
               existing_comment='Priority level: "high" or "normal" (default: normal)',
               existing_nullable=False)
    op.alter_column('todo', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               comment=None,
               existing_comment='Creation timestamp',
               existing_nullable=False)
    op.alter_column('todo', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               comment=None,
               existing_comment='Last update timestamp',
               existing_nullable=False)
    op.drop_index(op.f('idx_todo_completed'), table_name='todo')
    op.drop_index(op.f('idx_todo_created_at'), table_name='todo')
    op.drop_index(op.f('idx_todo_priority'), table_name='todo')
    op.drop_index(op.f('idx_todo_priority_created'), table_name='todo')
    op.drop_index(op.f('idx_todo_title'), table_name='todo', postgresql_ops={'title': 'text_pattern_ops'})
    op.drop_index(op.f('idx_todo_user_completed_created'), table_name='todo')
    op.drop_index(op.f('idx_todo_user_id'), table_name='todo')
    op.create_index(op.f('ix_todo_completed'), 'todo', ['completed'], unique=False)
    op.create_index(op.f('ix_todo_created_at'), 'todo', ['created_at'], unique=False)
    op.create_index(op.f('ix_todo_priority'), 'todo', ['priority'], unique=False)
    op.create_index(op.f('ix_todo_title'), 'todo', ['title'], unique=False)
    op.create_index(op.f('ix_todo_user_id'), 'todo', ['user_id'], unique=False)
    op.drop_constraint(op.f('todo_user_id_fkey'), 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'user', ['user_id'], ['id'])
    op.drop_table_comment(
        'todo',
        existing_comment='Todo items owned by users (user-scoped with CASCADE delete)',
        schema=None
    )
    op.add_column('user', sa.Column('language_preference', sqlmodel.sql.sqltypes.AutoString(length=2), server_default='en', nullable=False))
    op.alter_column('user', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               comment=None,
               existing_comment='Unique user identifier',
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Login email address (unique, indexed)',
               existing_nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Bcrypt-hashed password (never plain text)',
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="User's display name",
               existing_nullable=True)
    op.alter_column('user', 'email_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               comment=None,
               existing_comment='Account creation timestamp',
               existing_nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               comment=None,
               existing_comment='Last update timestamp',
               existing_nullable=False)
    op.drop_index(op.f('idx_user_created_at'), table_name='user')
    op.drop_index(op.f('idx_user_email'), table_name='user', postgresql_ops={'email': 'text_pattern_ops'})
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_table_comment(
        'user',
        existing_comment='User accounts with authentication and profile information',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'user',
        'User accounts with authentication and profile information',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_email'), 'user', ['email'], unique=True, postgresql_ops={'email': 'text_pattern_ops'})
    op.create_index(op.f('idx_user_created_at'), 'user', ['created_at'], unique=False)
    op.alter_column('user', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='Last update timestamp',
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='Account creation timestamp',
               existing_nullable=False)
    op.alter_column('user', 'email_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment="User's display name",
               existing_nullable=True)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='Bcrypt-hashed password (never plain text)',
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Login email address (unique, indexed)',
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               comment='Unique user identifier',
               existing_nullable=False)
    op.drop_column('user', 'language_preference')
    op.create_table_comment(
        'todo',
        'Todo items owned by users (user-scoped with CASCADE delete)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key(op.f('todo_user_id_fkey'), 'todo', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_todo_user_id'), table_name='todo')
    op.drop_index(op.f('ix_todo_title'), table_name='todo')
    op.drop_index(op.f('ix_todo_priority'), table_name='todo')
    op.drop_index(op.f('ix_todo_created_at'), table_name='todo')
    op.drop_index(op.f('ix_todo_completed'), table_name='todo')
    op.create_index(op.f('idx_todo_user_id'), 'todo', ['user_id'], unique=False)
    op.create_index(op.f('idx_todo_user_completed_created'), 'todo', ['user_id', 'completed', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_todo_title'), 'todo', ['title'], unique=False, postgresql_ops={'title': 'text_pattern_ops'})
    op.create_index(op.f('idx_todo_priority_created'), 'todo', ['priority', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_todo_priority'), 'todo', ['priority'], unique=False)
    op.create_index(op.f('idx_todo_created_at'), 'todo', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_todo_completed'), 'todo', ['completed'], unique=False)
    op.alter_column('todo', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='Last update timestamp',
               existing_nullable=False)
    op.alter_column('todo', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='Creation timestamp',
               existing_nullable=False)
    op.alter_column('todo', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'normal'::character varying"),
               comment='Priority level: "high" or "normal" (default: normal)',
               existing_nullable=False)
    op.alter_column('todo', 'completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment='Completion status (default: false)',
               existing_nullable=False)
    op.alter_column('todo', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               comment='Optional detailed description',
               existing_nullable=True)
    op.alter_column('todo', 'title',
               existing_type=sa.VARCHAR(length=500),
               comment='Todo title/summary (1-500 characters)',
               existing_nullable=False)
    op.alter_column('todo', 'user_id',
               existing_type=sa.UUID(),
               comment='Owner of the todo (foreign key to users.id, CASCADE on delete)',
               existing_nullable=False)
    op.alter_column('todo', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               comment='Unique todo identifier',
               existing_nullable=False)
    op.drop_index(op.f('ix_chat_message_session_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_created_at'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_chat_session_user_id'), table_name='chat_session')
    op.drop_index(op.f('ix_chat_session_last_activity_at'), table_name='chat_session')
    op.drop_table('chat_session')
    # ### end Alembic commands ###
